### ISSUE TITLE
Layout Exemplar documentation broken by stepEmitter/clock refactor

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/phet-lib#2]
Not working after https://github.com/phetsims/phet-lib/commit/7b8feca8a8630f7249617bb8e06aa8aa78d8f3d2.

I'm going to revert the commit, but thoughts on if I'm missing anything?

**Comment by jonathanolson** [comment]
Animation doc change was also incorrect, patched above.

**Comment by jonathanolson** [comment]
@pixelzoom can you review the revert commits above (and the original commits) to make sure this is all ok? layout exemplars (in phet-lib), layout docs (in scenery) were broken, and other documentation looked incorrect.

**Comment by pixelzoom** [comment]
Sorry about that -- I didn't notice that WebStorm used a wider scope for my rename in FEL.  Everything looks OK now.
