### ISSUE TITLE
Create TypeScript type definitions for phet-lib

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/phet-lib#3]
This would be helpful/necessary to really work with phet-lib in TypeScript. Ideally we'd build the type definitions along-side the JS code.

**Comment by samreid** [comment]
We added d.ts output in https://github.com/phetsims/chipper/issues/1424, next we need a way to bundle/include it with phet-lib.

**Comment by jonathanolson** [comment]
I've got the holy grail of an NPM package set up in testing (scenery-stack-test). Using https://github.com/phetsims/phet-vite-demo/commit/03eb9618128c697967821b409b84b885ad9992e7 (the scenery-stack-test branch of phet-vite-demo), I have a much more standard setup running:

<img width="415" alt="image" src="https://github.com/user-attachments/assets/0a342ef2-2cb6-4e6f-93bd-fb0bd493f95c">

It's type-safe (using TSC output for JS, d.ts, d.ts.map, and js.map), supports all of our common code, and seems to be working very swimmingly!

Example imports in a library: https://github.com/phetsims/phet-vite-demo/blob/scenery-stack-test/src/main.ts#L8-L16. It is type safe, and uses declaration/source maps so the development experience is up to par.

It also shows promise for how we might be able to link our dependencies easily in package.json (instead of awkwardly in sherpa, with type definition hackery): https://github.com/phetsims/scenery-stack-test/blob/main/package.json#L100-L115. I'm able to easily wrap those to provide globals (https://github.com/phetsims/scenery-stack-test/blob/main/src/minimal-preload.ts#L4-L33).

Current build approach is brittle. Figuring out "what translated strings do we include, and do we include translations" will be an interesting problem/question. It is NOT tree-shakeable right now.

**Comment by jonathanolson** [comment]
This has been completed for the scope of this issue, closing!
